default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000


development:
  <<: *default
  username: root
  password: 'mysql'
  database: inkbloom_dev


test:
  <<: *default
  username: root
  password: 'mysql'
  database: inkbloom_test


production:
  <<: *default
  username: root
  password: 'password'
  database: inkbloom_pd
